version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app

